# Generated by Django 3.0.7 on 2020-06-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
