# Generated by Django 3.0.7 on 2020-06-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prize',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
